resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:bcf792d990c03dbaed1a3b34278561ada2717bc4a94ea6e2a3716ec36356c239
  name: controller
  newName: registry.cn-hangzhou.aliyuncs.com/hb-chen/patch-operator:latest
