apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mutatingwebhookconfiguration-patcher
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mutatingwebhook-patcher
  namespace: patch-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mutatingwebhookconfiguration-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mutatingwebhookconfiguration-patcher
subjects:
  - kind: ServiceAccount
    name: mutatingwebhook-patcher
    namespace: patch-system