apiVersion: patch.hbchen.com/v1alpha1
kind: Patch
metadata:
  name: patch-sample
spec:
  # TODO(user): Add fields here
  serviceAccountRef:
    name: patch-controller-manager
  patches:
    test-complex-patch:
      targetObjectRef:
        apiVersion: v1
        kind: ServiceAccount
        name: default
        namespace: patch-system
      patchTemplate: |
        metadata:
          annotations:
            {{ (index . 1).metadata.name }}: {{ (index . 2).metadata.name }}
      patchType: application/merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          kind: Namespace
          name: patch-system
        - apiVersion: v1
          kind: ServiceAccount
          name: patch-controller-manager
          namespace: patch-system