apiVersion: patch.hbchen.com/v1alpha1
kind: Patch
metadata:
  name: patch-sample
spec:
  serviceAccountRef:
    name: patch-controller-manager
  patches:
    test-complex-patch:
      targetObjectRef:
        apiVersion: v1
        kind: ServiceAccount
        name: patch-controller-manager
        namespace: patch-system
      patchTemplate: |
        metadata:
          annotations:
            source-object-name-0: {{ (index . 0).metadata.name }}
            source-object-name-1: {{ (index . 1).metadata.name }}
            source-object-name-2: {{ (index . 2).metadata.name }}
      patchType: application/merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          kind: Namespace
          name: patch-system
        - apiVersion: v1
          kind: ServiceAccount
          name: patch-controller-manager
          namespace: patch-system